esphome:
  name: water-meter
  friendly_name: Water-meter

esp8266:
  board: d1_mini
  
logger:
  level: WARN

api:
  encryption:
    key: !secret water_meter_api_key

ota:
  - platform: esphome
    password: !secret water_meter_ota_password
  - platform: web_server

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  power_save_mode: LIGHT
  output_power: 20dBm
  ap:
    ssid: "Water-Meter Fallback Hotspot"
    password: !secret wifi_ap_password

packages:
  diagnostics:
    url: https://github.com/A-V-Kuzmich/home-assistant
    file: Wi-Fi-diagnostic.yaml
    refresh: 1d 

web_server:
  port: 80
  auth: 
    username: !secret web_server_user
    password: !secret web_server_pass

captive_portal:

debug:

globals:
  - id: empty_distance
    type: float
    initial_value: '1.45'  

  - id: calibration_work_distance
    type: float
    initial_value: '0.20' 

  - id: radius
    type: float
    initial_value: '0.3' 

  - id: calibration_factor
    type: float
    initial_value: '0.01'  
 # uptime  
  - id: timeout_counter
    type: int
    initial_value: '0'

  - id: total_timeouts
    type: int
    initial_value: '0'
    restore_value: yes

sensor:
  - platform: ultrasonic
    id: distance_sensor
    name: "distance"
    unit_of_measurement: "m"
    update_interval: 10s
    trigger_pin: 5
    echo_pin: 4
    filters:
      - median:
          window_size: 5
          send_every: 2
          send_first_at: 1
      - lambda: |-
          if (isnan(x)) {
            id(timeout_counter)++;
            id(total_timeouts)++;
            ESP_LOGW("distance_raw", "Timeouts: %d | Total: %d", id(timeout_counter), id(total_timeouts));
            if (id(timeout_counter) > 20) {
              ESP_LOGE("distance_raw", "TOO MANY TIMEOUTS — RESTARTING ESP!");
              ESP.restart();
            }
            return NAN;
          }
          id(timeout_counter) = 0;
          ESP_LOGI("distance_raw", "RAW DISTANCE = %.5f m", x);
          float corrected = x + id(calibration_factor);
          return corrected;
      - delta: 0.01
      - round: 2
    on_value:
      then:
        - lambda: |-
            float d = id(distance_sensor).state;
            if (isnan(d)) {
              id(liters_sensor).publish_state(0);
              id(percent_sensor).publish_state(0);
              return;
            }

            float work_zone = id(empty_distance) - id(calibration_work_distance);
            float radius_squared = id(radius) * id(radius);
            float level = work_zone - (d - id(calibration_work_distance));
            float volume_m3 = 3.14 * radius_squared * level;
            float percent = ((id(empty_distance) - d) / work_zone) * 100.0;

            if (percent < 0) percent = 0;

            id(liters_sensor).publish_state(volume_m3 * 1000.0);
            id(percent_sensor).publish_state(percent);

  - platform: template
    id: liters_sensor
    name: "Liters"
    unit_of_measurement: "л"
    accuracy_decimals: 1
    icon: "mdi:barrel"
    update_interval: never 

  - platform: template
    id: percent_sensor
    name: "%"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:water-percent"
    update_interval: never 

number:
  - &calibration_numbers
    platform: template
    name: "Empty distanse"
    id: empty_distance_correction
    entity_category: "diagnostic"
    icon: "mdi:calculator-variant"
    min_value: 0.01
    max_value: 3.00
    step: 0.01
    mode: box
    lambda: "return id(empty_distance);"
    set_action:
      then:
        - lambda: "id(empty_distance) = x;"

  - <<: *calibration_numbers
    name: "Work distance"
    id: work_distance_correction
    lambda: "return id(calibration_work_distance);"
    set_action:
      then:
        - lambda: "id(calibration_work_distance) = x;"

  - <<: *calibration_numbers
    name: "radius"
    id: radius_correction
    lambda: "return id(radius);"
    set_action:
      then:
        - lambda: "id(radius) = x;"

  - <<: *calibration_numbers
    name: "calibration_factor"
    id: factor_correction
    lambda: "return id(calibration_factor);"
    set_action:
      then:
        - lambda: "id(calibration_factor) = x;"

text_sensor:
  - platform: debug
    reset_reason:
      name: "Last Reset Reason"
      id: last_reset_reason
      entity_category: "diagnostic"
      icon: "mdi:restart-alert"
